[2022-07-12 09:07:53,182] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: LocalIngestionDAD.ingest scheduled__2022-04-05T06:00:00+00:00 [queued]>
[2022-07-12 09:07:53,201] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: LocalIngestionDAD.ingest scheduled__2022-04-05T06:00:00+00:00 [queued]>
[2022-07-12 09:07:53,202] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 09:07:53,203] {taskinstance.py:1357} INFO - Starting attempt 3 of 3
[2022-07-12 09:07:53,203] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 09:07:53,231] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): ingest> on 2022-04-05 06:00:00+00:00
[2022-07-12 09:07:53,240] {standard_task_runner.py:52} INFO - Started process 2389 to run task
[2022-07-12 09:07:53,244] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDAD', 'ingest', 'scheduled__2022-04-05T06:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_postgres.py', '--cfg-path', '/tmp/tmp_2n4khwh', '--error-file', '/tmp/tmpunfbxxn3']
[2022-07-12 09:07:53,246] {standard_task_runner.py:80} INFO - Job 27: Subtask ingest
[2022-07-12 09:07:53,342] {task_command.py:370} INFO - Running <TaskInstance: LocalIngestionDAD.ingest scheduled__2022-04-05T06:00:00+00:00 [running]> on host ef58f039b0e2
[2022-07-12 09:07:53,435] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-07-12 09:07:53,521] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDAD
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2022-04-05T06:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-05T06:00:00+00:00
[2022-07-12 09:07:53,620] {logging_mixin.py:115} INFO - connection established successfully, inserting data...
[2022-07-12 09:07:53,633] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_postgres.py", line 19, in ingest_postgres
    df.head(n=0).to_sql(name=dtb_table_name, con=engine, if_exists='replace')
UnboundLocalError: local variable 'df' referenced before assignment
[2022-07-12 09:07:53,663] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=LocalIngestionDAD, task_id=ingest, execution_date=20220405T060000, start_date=20220712T090753, end_date=20220712T090753
[2022-07-12 09:07:53,689] {standard_task_runner.py:97} ERROR - Failed to execute job 27 for task ingest (local variable 'df' referenced before assignment; 2389)
[2022-07-12 09:07:53,702] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-12 09:07:53,763] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
